api/src/main/resources/messages_es.properties
omod/src/main/resources/config.xml

Here it is a translation file for Spanish language. Some of the strings in the module are hard-coded, so the module is partially translated. Anyway, I think that it is a good starting point.

Added messages_es.properties file

---

README.md

Updated README to improve readability

---

.gitignore
api-tests/src/test/java/org/openmrs/module/reporting/data/visit/evaluator/SqlVisitDataEvaluatorTest.java
api-tests/src/test/java/org/openmrs/module/reporting/definition/library/AllDefinitionLibrariesComponentTest.java
api-tests/src/test/java/org/openmrs/module/reporting/definition/library/implementerconfigured/ImplementerConfiguredCohortDefinitionLibraryTest.java
api-tests/src/test/java/org/openmrs/module/reporting/definition/library/implementerconfigured/ImplementerConfiguredDataSetDefinitionLibraryTest.java
api-tests/src/test/java/org/openmrs/module/reporting/definition/library/implementerconfigured/ImplementerConfiguredEncounterDataDefinitionLibraryTest.java
api-tests/src/test/java/org/openmrs/module/reporting/definition/library/implementerconfigured/ImplementerConfiguredPatientDataDefinitionLibraryTest.java
api-tests/src/test/java/org/openmrs/module/reporting/definition/library/implementerconfigured/ImplementerConfiguredVisitDataDefinitionLibraryTest.java
api/src/main/java/org/openmrs/module/reporting/data/visit/definition/SqlVisitDataDefinition.java
api/src/main/java/org/openmrs/module/reporting/data/visit/evaluator/SqlVisitDataEvaluator.java
api/src/main/java/org/openmrs/module/reporting/definition/library/implementerconfigured/BaseImplementerConfiguredDefinitionLibrary.java
api/src/main/java/org/openmrs/module/reporting/definition/library/implementerconfigured/ImplementerConfiguredCohortDefinitionLibrary.java
api/src/main/java/org/openmrs/module/reporting/definition/library/implementerconfigured/ImplementerConfiguredDataSetDefinitionLibrary.java
api/src/main/java/org/openmrs/module/reporting/definition/library/implementerconfigured/ImplementerConfiguredEncounterDataDefinitionLibrary.java
api/src/main/java/org/openmrs/module/reporting/definition/library/implementerconfigured/ImplementerConfiguredPatientDataDefinitionLibrary.java
api/src/main/java/org/openmrs/module/reporting/definition/library/implementerconfigured/ImplementerConfiguredVisitDataDefinitionLibrary.java
pom.xml

also REPORT-768 - Add SqlVisitDataSetDefinition and Evaluator

REPORT-761 - Automatically load definitions at startup

---

api/src/main/resources/liquibase.xml

see https://issues.openmrs.org/browse/REPORT-767

REPORT-767 Refactor liquibase.xml for H2 compatibility

---

README.md

https://issues.openmrs.org/browse/REPORT-792

REPORT-792: README is missing a dependency

---

api/src/main/java/org/openmrs/module/reporting/cohort/definition/library/BuiltInCohortDefinitionLibrary.java

[REPORT-808](https://issues.openmrs.org/browse/REPORT-808): Add programEnrollment to BuiltInCohortDefinitionLibrary
Add programEnrollment definition library key to BuiltInCohortDefinitionLibrary

Report-808: Add programEnrollment to BuiltInCohortDefinitionLibrary

---

api/src/main/java/org/openmrs/module/reporting/cohort/definition/library/BuiltInCohortDefinitionLibrary.java

REPORT-803: Add observation search definition library
Add codedObsSearchAdvanced cohort definition library for making observation searches.

REPORT-803: Add observation cohort definition library

---

api-tests/src/test/java/org/openmrs/module/reporting/query/visit/evaluator/BasicVisitQueryEvaluatorTest.java
api/src/main/java/org/openmrs/module/reporting/query/visit/definition/BasicVisitQuery.java
api/src/main/java/org/openmrs/module/reporting/query/visit/evaluator/BasicVisitQueryEvaluator.java

Following Talk thread:
https://talk.openmrs.org/t/reporting-module-only-one-visit-is-displayed-from-my-evaluated-datasetdefinition/12371/16?u=mksrom

Add a BasicVisitQuery to filter visits by date, type and location

---

api-tests/src/test/java/org/openmrs/module/reporting/data/visit/evaluator/ObsForVisitDataEvaluatorTest.java
api/src/main/java/org/openmrs/module/reporting/data/visit/definition/ObsForVisitDataDefinition.java
api/src/main/java/org/openmrs/module/reporting/data/visit/evaluator/ObsForVisitDataEvaluator.java

https://talk.openmrs.org/t/reporting-module-can-we-really-use-obsforpersondatadefinition-in-a-visitdataset/12713?u=mksrom

Add a ObsForVisitDataDefintion to fetch observations of a visit

---

api-tests/src/test/java/org/openmrs/module/reporting/report/definition/service/ReportDefinitionServiceImplTest.java
api-tests/src/test/java/org/openmrs/module/reporting/report/service/ReportServiceTest.java
api-tests/src/test/resources/org/openmrs/module/reporting/include/ReportDefinitionServiceImplTest.xml
api-tests/src/test/resources/org/openmrs/module/reporting/include/ReportTestDataset-openmrs-1.10.xml
api-tests/src/test/resources/org/openmrs/module/reporting/include/ReportTestDataset-openmrs-1.11.xml
api-tests/src/test/resources/org/openmrs/module/reporting/include/ReportTestDataset-openmrs-1.12.xml
api-tests/src/test/resources/org/openmrs/module/reporting/include/ReportTestDataset-openmrs-1.9.xml
api-tests/src/test/resources/org/openmrs/module/reporting/include/ReportTestDataset-openmrs-2.0.xml
api/src/main/java/org/openmrs/module/reporting/report/definition/service/ReportDefinitionService.java
api/src/main/java/org/openmrs/module/reporting/report/definition/service/ReportDefinitionServiceImpl.java
api/src/main/java/org/openmrs/module/reporting/report/service/ReportService.java
api/src/main/java/org/openmrs/module/reporting/report/service/ReportServiceImpl.java
api/src/main/java/org/openmrs/module/reporting/report/service/db/HibernateReportDAO.java
api/src/main/java/org/openmrs/module/reporting/report/service/db/ReportDAO.java

https://issues.openmrs.org/browse/REPORT-580

REPORT-580 Allow purging of report definitions by UUID

---

api/src/main/resources/messages.properties
omod/src/main/java/org/openmrs/module/reporting/web/datasets/ManageDatasetsController.java
omod/src/main/webapp/datasets/datasetEditor.jsp

…on editing a particular dataSet.
Ticket: https://issues.openmrs.org/browse/REPORT-420

REPORT-420:Added attribute of viewing affected Report Defs on the UI on editing a particular dataSet

---

api-1.10/.gitignore
api-1.10/pom.xml
api-1.10/src/main/java/org/openmrs/module/reporting/cohort/definition/DrugOrderCohortDefinition.java
api-1.10/src/main/java/org/openmrs/module/reporting/cohort/definition/evaluator/DrugOrderCohortDefinitionEvaluator.java
api-1.10/src/main/java/org/openmrs/module/reporting/cohort/definition/library/BuiltInCohortDefinitionLibrary1_10.java
api-1.10/src/test/java/org/openmrs/module/reporting/cohort/definition/evaluator/DrugOrderCohortDefinitionEvaluatorTest.java
api-1.10/src/test/java/org/openmrs/module/reporting/cohort/definition/library/BuiltInCohortDefinitionLibrary1_10Test.java
api-1.10/src/test/resources/org/openmrs/module/reporting/include/DrugOrderCohortEvaluationData.xml
api/src/main/java/org/openmrs/module/reporting/common/Match.java
api/src/main/java/org/openmrs/module/reporting/evaluation/querybuilder/HqlQueryBuilder.java
omod/src/main/resources/config.xml
pom.xml

Ticket : https://issues.openmrs.org/browse/REPORT-838

REPORT-838 : Update Drug Order Filter

---

api-tests/src/test/java/org/openmrs/module/reporting/data/encounter/evaluator/ObsOnSameDateEncounterDataEvaluatorTest.java
api/src/main/java/org/openmrs/module/reporting/data/encounter/definition/ObsOnSameDateEncounterDataDefinition.java
api/src/main/java/org/openmrs/module/reporting/data/encounter/evaluator/ObsOnSameDateEncounterDataEvaluator.java

Hi @mseaton , here is the code you sent me last week. It worked out quite well! I added a unit test and I was able to use it in pihmalawi too. Thanks for reviewing this code.

REPORT-852, implement ObsOnSameDateEncounterDataDefinition

---

api/src/main/java/org/openmrs/module/reporting/cohort/definition/library/BuiltInCohortDefinitionLibrary.java

Ticket : https://issues.openmrs.org/browse/REPORT-855

REPORT-855 : Improved the BuiltInCohortDefinitionLibrary For Coded_obs and text_obs

---

api-2.2/src/main/java/org/openmrs/module/reporting/cohort/definition/evaluator/ConditionCohortDefinitionEvaluator.java

Ticket : https://issues.openmrs.org/browse/REPORT-856
Follow up commit to Include onset and End dates in ActiveOnDate

REPORT-856: ActiveOnDate should Include onset and End dates

---

api/src/main/java/org/openmrs/module/reporting/report/renderer/ReportTemplateRenderer.java

https://issues.openmrs.org/browse/REPORT-861:Make Reports Return an IndicatorResult Datatype

REPORT-861:Make Reports Return an IndicatorResult Datatype

---

api/src/main/resources/ReportDesign.hbm.xml
api/src/main/resources/ReportRequest.hbm.xml

**Changes I Made**
Mapped Sequence correctly
**Link to ticket** 
https://issues.openmrs.org/browse/REPORT-866

REPORT-866 Properly map the sequences via hibernate

---

api/src/main/resources/liquibase.xml

**Changes I did**
Changed tinyint(1) to boolean
**Link to ticket**
https://issues.openmrs.org/browse/REPORT-869

Report 869  Change tinyint(1) to boolean for boolean columns in Reporting Module

---

omod/src/main/java/org/openmrs/module/reporting/web/controller/portlet/ReportProcessorFormController.java
pom.xml

@isears 
Added input sanitization for Name field in Add Report Processor Form.
This fix protects against the Reflective XSS vulnerability in the form. The bug can be reproduced by following the steps mentioned [here]https://docs.google.com/document/d/14iBloBvhokfKHfV1KBMSPmmrMHabAWdh1x6awLXrtb0/edit?usp=sharing).
https://issues.openmrs.org/browse/RA-1865

RA1865 - Adding HTML Encoding for Report Processor Name

---

omod/src/main/webapp/definition/manageDefinitions.jsp
omod/src/main/webapp/indicators/manageIndicators.jsp
omod/src/main/webapp/portlets/baseCohortIndicator.jsp

@isears:
**Why:**
Possible XSS bugs while creating cohort indicator and queries. Step to reproduce the bugs can be found [here](https://docs.google.com/document/d/1ZQ4l-HBP7ooUn-1sU3Bd8u3WEvL6uqvbao6bYDPGhRg/edit?usp=sharing)
**Decisions made:**
Modified the confirmDelete function so that the inclusion of a single quote in the name field does not interfere with the intended functionality.

 RA-1865: Patch bugs discovered by NCSU team 

---

omod/src/main/java/org/openmrs/module/reporting/web/reports/ManageReportsController.java

Ticket issue: https://issues.openmrs.org/browse/REPORT-878

REPORT-878:Enable RenderReport Method to accept multiple values a single parameter from a HTTP Rquest

---

api/src/main/resources/liquibase.xml

- Increased reporting_report_design_resource.content_type to varchar(100),
so it can fir the XLSX content type value

REPORT-870: Increased size of ReportDesignResource.contentType DB column

---

api/src/main/resources/liquibase.xml

I added `mariadb` to the dbms attribute of changeset `reporting_report_design_2` and `reporting_report_design_3` and added `validCheckSum` value from existing MySQL database.
see https://issues.openmrs.org/browse/REPORT-888
- [ x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`
- [ x] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)
No? -> write tests and add them to this commit `git add . && git commit --amend`
- [ x] I ran `mvn clean package` right before …

REPORT-888 - Add MariaDb into changeSet Entries

---

api/pom.xml
omod/pom.xml
omod/src/main/resources/config.xml

- The purpose of this PR is to fix #[REPORT-890](https://issues.openmrs.org/browse/REPORT-890)
- To add the drug order filter support for the ad-hoc query
- Added the missing api module dependency

REPORT-890: Add the missing api module dependency

---

omod/src/main/resources/config.xml

- The purpose of this PR is to fix #[REPORT-890](https://issues.openmrs.org/browse/REPORT-890)
- To fix the drug order filter not working in the OMRS 3.x cohort builder
- Updated the openMRS version for the api 1.10

REPORT-890: Update the openMRS version for the api 1.10
